// source: query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.Query', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Query = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.Query.displayName = 'proto.Query';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.Query.prototype.toObject = function(opt_includeInstance) {
        return proto.Query.toObject(opt_includeInstance, this);
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.Query} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.Query.toObject = function(includeInstance, msg) {
        var f,
            obj = {
                id: jspb.Message.getFieldWithDefault(msg, 1, ''),
                text: jspb.Message.getFieldWithDefault(msg, 2, ''),
                paramsMap: (f = msg.getParamsMap())
                    ? f.toObject(
                          includeInstance,
                          proto.google.protobuf.Any.toObject,
                      )
                    : [],
                cdp: jspb.Message.getFieldWithDefault(msg, 4, ''),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Query}
 */
proto.Query.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.Query();
    return proto.Query.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Query}
 */
proto.Query.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setId(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setText(value);
                break;
            case 3:
                var value = msg.getParamsMap();
                reader.readMessage(value, function(message, reader) {
                    jspb.Map.deserializeBinary(
                        message,
                        reader,
                        jspb.BinaryReader.prototype.readString,
                        jspb.BinaryReader.prototype.readMessage,
                        proto.google.protobuf.Any.deserializeBinaryFromReader,
                        '',
                    );
                });
                break;
            case 4:
                var value = /** @type {string} */ (reader.readString());
                msg.setCdp(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Query.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.Query.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Query.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getId();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getText();
    if (f.length > 0) {
        writer.writeString(2, f);
    }
    f = message.getParamsMap(true);
    if (f && f.getLength() > 0) {
        f.serializeBinary(
            3,
            writer,
            jspb.BinaryWriter.prototype.writeString,
            jspb.BinaryWriter.prototype.writeMessage,
            proto.google.protobuf.Any.serializeBinaryToWriter,
        );
    }
    f = message.getCdp();
    if (f.length > 0) {
        writer.writeString(4, f);
    }
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.Query.prototype.getId = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        '',
    ));
};

/** @param {string} value */
proto.Query.prototype.setId = function(value) {
    jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string text = 2;
 * @return {string}
 */
proto.Query.prototype.getText = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        2,
        '',
    ));
};

/** @param {string} value */
proto.Query.prototype.setText = function(value) {
    jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * map<string, google.protobuf.Any> params = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Any>}
 */
proto.Query.prototype.getParamsMap = function(opt_noLazyCreate) {
    return /** @type {!jspb.Map<string,!proto.google.protobuf.Any>} */ (jspb.Message.getMapField(
        this,
        3,
        opt_noLazyCreate,
        proto.google.protobuf.Any,
    ));
};

/**
 * Clears values from the map. The map will be non-null.
 */
proto.Query.prototype.clearParamsMap = function() {
    this.getParamsMap().clear();
};

/**
 * optional string cdp = 4;
 * @return {string}
 */
proto.Query.prototype.getCdp = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        4,
        '',
    ));
};

/** @param {string} value */
proto.Query.prototype.setCdp = function(value) {
    jspb.Message.setProto3StringField(this, 4, value);
};

goog.object.extend(exports, proto);
